[package]
name = "erhino_kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
erhino_shared = { path = "../../shared" }
dtb = { path = "../dtb" }
lock_api = "0.4"
talc = "5"
page_table = { path = "../page_table" }
frame_pool = { path = "../frame_pool" }
elf = { path = "../elf" }
sched_domain = { path = "../sched_domain" }
handle_table = { path = "../handle_table" }
wait_context = { path = "../wait_context" }
timer_queue = { path = "../timer_queue" }
stack_layout = { path = "../stack_layout" }
remote_call = { path = "../remote_call" }
memory_space = { path = "../memory_space" }
memory_supply = { path = "../memory_supply" }
memory_pool = { path = "../memory_pool" }
funded_frame = { path = "../funded_frame" }
metadata_admission = { path = "../metadata_admission" }
num-traits = { version = "0.2", default-features = false }
