[workspace]
members = [
    "rinlib",
    "services/srv_init",
    "services/srv_fs",
    "services/srv_pm",
    "drivers/drv_spi_sifive",
    "tests/test_fp",
    "tests/test_fal",
    "tests/test_hammer",
    "tests/test_target",
    "libraries/libbudget",
    "libraries/libexecution",
    "libraries/libfal",
    "libraries/libservice",
    "libraries/libfs",
    "libraries/librpc",
    "libraries/librunnel",
    "libraries/libprocess",
]
resolver = "2"
