[workspace]
members = [
    "rinlib",
    "services/srv_init",
    "services/srv_fs",
    "services/srv_pm",
    "drivers/drv_spi_sifive",
    "tests/test_fp",
    "tests/test_hammer",
    "tests/test_target",
    "frameworks/libsrv",
    "frameworks/libdrv",
    "frameworks/libfal",
    "frameworks/libfs",
    "frameworks/librpc",
    "frameworks/librunnel",
    "frameworks/libprocess",
]
resolver = "2"
