[workspace]
members = [
    "rinlib",
    "systems/init",
    "systems/fs",
    "systems/pm",
    "frameworks/libsrv",
    "frameworks/libdrv",
    "frameworks/libfal",
    "frameworks/libfs",
    "frameworks/librpc",
    "frameworks/librunnel",
    "frameworks/libprocess",
    "drivers/spi_sifive"
]
resolver = "2"
