[package]
name = "srv_init"
version = "0.1.0"
authors = ["Chien Zhang (zqy0224@live.com)"]
description = "Power of kzios userspace"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rinlib = { path = "../../rinlib" }
librunnel = { path = "../../frameworks/librunnel" }
libprocess = { path = "../../frameworks/libprocess" }
tar = { path = "../../../os/tar" }
